### ISSUE TITLE
Load finetuned model and generate predictions

### ISSUE THREAD

**Issue by gsinapi** [pbmstrk/arxiv-generator#3]
Hi,

I have run the filetune.py file for fine tuning the model on a custom dataset and saved the finetuned model in the checkpoints folder as 'epoch=0.ckpt'. 

How do I load this new finetuned model and generate predictions? Using AutoModelForSeq2SeqLM.from_pretrained('checkpoints/epoch=0.ckpt') does not seem to work.

Thanks

**Comment by pbmstrk** [comment]
To load the fine-tuned model,

```python
from arxiv_generator import Seq2SeqGenerator
model = Seq2SeqGenerator.load_from_checkpoint(checkpoint_path="./checkpoints/epoch=0.ckpt")
```

Loading the model using `AutoModelForSeq2SeqLM.from_pretrained(...)` will only work if the model is uploaded on the Huggingface Model Hub.

**Comment by gsinapi** [comment]
Thanks! I was able to load the model, but when I try to generate predictions (using the `generate_predictions(abstract, model, tokenizer, args)` function), I get the following error at the `model.generate` method:

`~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1850         # remove once script supports set_grad_enabled
   1851         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1852     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1853
   1854

IndexError: index out of range in self
`

Do you think there might be a mismatch between the tokenizer vocabulary size (I am using the tokenizer from facebook/bart-large', the one in the config file) and the new model checkpoint? 

Thanks.

**Comment by pbmstrk** [comment]
Yes, a mismatch between tokenizer and model can cause problems. Another possibility is that the sequence you are passing is too long. That is, the length of tokenized sequence is larger than the maximum sequence length for the model - try truncating the input.
